### ISSUE TITLE
Links to articles.

### ISSUE THREAD

**Issue by RhodesPeter** [GlobeTownDevs/api#25]
This is more about functionality than the code but could you create links so that the images link to the articles on their home websites?

There doesn't seem to be a huge benefit from the article getting smaller when you click on it
I would possibly reverse this so that when you click on the articles you get more information rather than less.

**Comment by emilyb7** [comment]
agree about the links! 👍

**Comment by tbtommyb** [comment]
Good point. The articles shouldn't get smaller when you click on them on a laptop-sized screen. They should only toggle on small screens so thanks for flagging that too.
