### ISSUE TITLE
Set up news api requests per source and test asynchronously

### ISSUE THREAD

**Issue by marisid** [GlobeTownDevs/api#4]
# Steps

1. Make sources request
2. From response, for each sources item, store source id into an array (e.g. "bbc-news", "mirror" etc). *Optional:* Save source id logo and hyperlink for displaying next to headlines
3. For each source id in the array, make an article request, ideally using SortBy 'top' if available for that source
4. From response, pick first 5 headlines (for testing purposes)per source and push them into a new object
5. Pass the headlines object for Text Rasor API requests following the format below (see Nick's comment)

**Comment by njsfield** [comment]
## JSON To Parse To TextRazor Example

A global object could hold much more information, including JSON urls to articles, urls to images/logos, date article created etc. But the core information parsed to TextRazor would appear like this:

``` javascript

var jsonToGoToTextRazor = {
    bbc-news: [
        'headline1 description',
        'headline2 description',
        'headline3 description'
    ],
    mirror: [
        'headline1 description',
        'headline2 description',
        'headline3 description'
    ],
    mail: [
        'headline3 description',
        'headline4 description'
    ]
}

```

**Comment by marisid** [comment]
## Async tests
- Should wait for sources array to be completed before continuing with article requests
- Should wait for each article request completed before moving on to the next article request
- Should update the headlines object at the end of each article request

**Comment by tbtommyb** [comment]
So are we sending headlines from multiple newspapers to be analysed or are we choosing individual newspapers?

**Comment by marisid** [comment]
Good point @tbtommyb. The json headline object will contain headlines from a single source, as selected by the user before fetching any news feed. (update to step 3 above: make an article request for a selected source from the available sources array - maybe a dropdown list?  TBC)
